// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUAxTmbnKft5SaAQ1KOFcthTOEzgGhJLw',
    appId: '1:106089965852:web:44eab8b426d2ec558bb2d9',
    messagingSenderId: '106089965852',
    projectId: 'chat-app-49b97',
    authDomain: 'chat-app-49b97.firebaseapp.com',
    storageBucket: 'chat-app-49b97.appspot.com',
    measurementId: 'G-X6LRQ94WCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPmnJOW968bqaRTBKsJ0QjnSASjHK29b0',
    appId: '1:106089965852:android:8ab863fb341898158bb2d9',
    messagingSenderId: '106089965852',
    projectId: 'chat-app-49b97',
    storageBucket: 'chat-app-49b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeFCk1AhyO-pZaHDoGXYrOcJaHOhUk7yo',
    appId: '1:106089965852:ios:c41f2183299adee18bb2d9',
    messagingSenderId: '106089965852',
    projectId: 'chat-app-49b97',
    storageBucket: 'chat-app-49b97.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeFCk1AhyO-pZaHDoGXYrOcJaHOhUk7yo',
    appId: '1:106089965852:ios:c41f2183299adee18bb2d9',
    messagingSenderId: '106089965852',
    projectId: 'chat-app-49b97',
    storageBucket: 'chat-app-49b97.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUAxTmbnKft5SaAQ1KOFcthTOEzgGhJLw',
    appId: '1:106089965852:web:6d5cf4db184d2b958bb2d9',
    messagingSenderId: '106089965852',
    projectId: 'chat-app-49b97',
    authDomain: 'chat-app-49b97.firebaseapp.com',
    storageBucket: 'chat-app-49b97.appspot.com',
    measurementId: 'G-X30W29S6FP',
  );

}